apiVersion: v1
kind: Service
metadata:
  name: review-svc
  labels:
    app: review
    project: shop-app
spec:
  selector:
    app: review
  ports:
    - protocol: TCP
      name: review-port
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review
    project: shop-app
    app.kubernetes.io/part-of: shop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
      project: shop-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: review
        project: shop-app
      annotations:
        linkerd.io/inject: enabled
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - image: review:latest
          name: review
          imagePullPolicy: Never
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: review-port
              containerPort: 8080
      restartPolicy: Always

