apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user
    project: shop-app
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: user-port
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
    project: shop-app
    app.kubernetes.io/part-of: shop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      project: shop-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
        project: shop-app
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: linkerd-collector.linkerd:55678
        config.alpha.linkerd.io/trace-collector-service-account: linkerd-collector
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - image: user:latest
          name: user
          imagePullPolicy: Never
          # args: ["prod:user"]
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
          ports:
            - name: user-port
              containerPort: 8080
      restartPolicy: Always
