apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    app: product
    project: shop-app
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      name: product-port
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
    project: shop-app
    app.kubernetes.io/part-of: shop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
      project: shop-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: product
        project: shop-app
      annotations:
        linkerd.io/inject: enabled
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - image: product:latest
          name: product
          imagePullPolicy: Never
          # args: ["prod:user"]
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: product-port
              containerPort: 8080
      restartPolicy: Always
